local WeaponList={"Shared","Zeus","Pistol","Heavy Pistol","Submachine Gun","Rifle","Shotgun","Scout","Auto Sniper","Sniper","Light Machine Gun"}

local RF=gui.Reference

local function NM(RFName,SetName)  RFName:SetName(SetName)  end

NM(RF("Configurations"),"参数")
    NM(RF("参数", "Local"),"本地")

NM(RF("Lua Scripts"),"Lua脚本")
    NM(RF("Lua脚本", "Local"),"本地")
    NM(RF("Lua脚本", "Security"),"安全")
        NM(RF("Lua脚本", "安全", "Allow scripts to edit lua files"),"允许脚本编辑lua文件")
        NM(RF("Lua脚本", "安全", "Allow scripts to edit cfg files"),"允许脚本编辑cfg文件")
        NM(RF("Lua脚本", "安全", "Allow internet connections"),"允许网络连接")
        NM(RF("Lua脚本", "安全", "Allow game scripting"),"允许游戏脚本")
        NM(RF("Lua脚本", "安全", "Allow insecure FFI"),"允许不安全的FFI")
        NM(RF("Lua脚本", "安全", "Save Lua Permissions"),"保存Lua权限")
    NM(RF("Lua脚本", "Other"),"其它")
        NM(RF("Lua脚本", "其它", "Load With Configurations"),"随参数加载")

NM(RF("Legitbot"),"合法")
    NM(RF("合法", "Aimbot"),"自瞄")
        NM(RF("合法", "自瞄", "Main"),"主要")
            NM(RF("合法", "自瞄", "主要", "Enable"),"启用")
            NM(RF("合法", "自瞄", "主要", "Aim Key"),"热键")
            NM(RF("合法", "自瞄", "主要", "Auto Pistol Interval"),"自动手枪间隔")
        NM(RF("合法", "自瞄", "Hitbox Selection"),"自瞄部位选择")
            for i = 1, 11, 1 do
                NM(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "Hitbox Advance Multiplier"),"自瞄部位切换速度")
                NM(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "Nearest To Crosshair"),"准星附近优先")
            end
    NM(RF("合法", "Triggerbot"),"扳机")
        NM(RF("合法", "扳机", "Main"),"主要")
            NM(RF("合法", "扳机", "主要", "Enable"),"启用")
            NM(RF("合法", "扳机", "主要", "Trigger Key"),"热键")
            NM(RF("合法", "扳机", "主要", "Auto Fire"),"自动开火")
            NM(RF("合法", "扳机", "主要", "Knife Triggerbot"),"刀扳机")
        NM(RF("合法", "扳机", "Weapon"),"武器")
            for i = 1, 11, 1 do
                NM(RF("合法", "扳机", "武器", WeaponList[i], "Trigger Delay"),"扳机延迟")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "Trigger Burst"),"扳机连发")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "Hit Chance"),"命中率")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "Accuracy"),"精度提升")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "精度提升", "Anti-Recoil"),"反后座")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "精度提升", "Anti-Spread"),"反扩散")
            end
        NM(RF("合法", "扳机", "Hitboxes"),"部位")
    NM(RF("合法", "Weapon"),"武器")
        NM(RF("合法", "武器", "Accuracy"),"压枪")
            for i = 1, 11, 1 do
                NM(RF("合法", "武器","压枪", WeaponList[i], "Recoil Control System"),"压枪时机")
                    RF("合法", "武器","压枪", WeaponList[i], "压枪时机"):SetOptions("关闭","自瞄时","独立")
                NM(RF("合法", "武器","压枪", WeaponList[i], "Horizontal Recoil"),"横向压枪")
                NM(RF("合法", "武器","压枪", WeaponList[i], "Vertical Recoil"),"纵向压枪")
            end
        NM(RF("合法", "武器", "Target"),"目标")
            for i = 1, 11, 1 do
                NM(RF("合法", "武器", "目标", WeaponList[i], "Minimum FOV Range"),"最小范围")
                NM(RF("合法", "武器", "目标", WeaponList[i], "Maximum FOV Range"),"最大范围")
                NM(RF("合法", "武器", "目标", WeaponList[i], "Non-Sticky Target"),"超过范围不自瞄")
                NM(RF("合法", "武器", "目标", WeaponList[i], "Target Switch Delay"),"目标切换延迟")
                NM(RF("合法", "武器", "目标", WeaponList[i], "First Shot Delay"),"首次射击延迟")
            end
        NM(RF("合法", "武器", "Aiming"),"瞄准")
            for i = 1, 11, 1 do
                NM(RF("合法", "武器", "瞄准", WeaponList[i], "Smooth Factor"),"平滑因子")
                NM(RF("合法", "武器", "瞄准", WeaponList[i], "Smooth Method"),"平滑方式")
                    RF("合法", "武器", "瞄准", WeaponList[i], "平滑方式"):SetOptions("动态", "静态")
                NM(RF("合法", "武器", "瞄准", WeaponList[i], "Randomize Factor"),"随机因子")
                NM(RF("合法", "武器", "瞄准", WeaponList[i], "Curve Factor"),"曲线因子")
            end
        NM(RF("合法", "武器", "Visibility"),"可见性")
            for i = 1, 11, 1 do
                NM(RF("合法", "武器", "可见性", WeaponList[i], "Auto Wall"),"穿墙")
                NM(RF("合法", "武器", "可见性", WeaponList[i], "Through Smoke"),"穿烟")
            end

NM(RF("Ragebot"),"暴力")
    NM(RF("暴力", "Main"),"主要")
        NM(RF("暴力", "主要", "Enabled"),"启用")
        NM(RF("暴力", "主要", "Silent Aim"),"静默")
        NM(RF("暴力", "主要", "Backtrack"),"回溯")
        NM(RF("暴力", "主要", "Anti-Recoil"),"无后座")
        NM(RF("暴力", "主要", "Anti-Spread"),"无扩散")
        NM(RF("暴力", "主要", "Target Selection"),"目标选择")
            RF("暴力", "主要", "目标选择"):SetOptions("最低血量", "距离最近", "准星最近")
        NM(RF("暴力", "主要", "FOV"),"范围")
        NM(RF("暴力", "主要", "Knifebot"),"自动刀")
            RF("暴力", "主要", "自动刀"):SetOptions("关闭","默认","仅背刺","快速刀")
        NM(RF("暴力", "主要", "Duck Peek assist"),"假蹲")
    NM(RF("暴力", "Anti-Aim"),"反自瞄")
        NM(RF("暴力", "反自瞄", "Enabled"),"启用")
        NM(RF("暴力", "反自瞄", "Pitch Angle"),"俯仰角度")
            RF("暴力", "反自瞄", "俯仰角度"):SetOptions("关闭","低头","抬头","假抬头","平视")
        NM(RF("暴力", "反自瞄", "Yaw Angle"),"偏航角度")
            RF("暴力", "反自瞄", "偏航角度"):SetOptions("朝前","背身")
        NM(RF("暴力", "反自瞄", "Auto Direction"),"自动朝向")
            NM(RF("暴力", "反自瞄", "自动朝向", "At Edges"),"墙边藏头")
            NM(RF("暴力", "反自瞄", "自动朝向", "At Targets"),"朝向目标")
        NM(RF("暴力", "反自瞄", "Disable Conditions"),"禁用条件")
            NM(RF("暴力", "反自瞄", "禁用条件", "On Use"),"交互时")
            NM(RF("暴力", "反自瞄", "禁用条件", "On Knife"),"持刀时")
            NM(RF("暴力", "反自瞄", "禁用条件", "On Grenade"),"持道具时")
            NM(RF("暴力", "反自瞄", "禁用条件", "During Freeze Time"),"回合冻结时")
    NM(RF("暴力", "Auto Peek"),"自动Peek")
        NM(RF("暴力", "自动Peek", "Enable"),"启用")
        NM(RF("暴力", "自动Peek", "Key"),"热键")
        NM(RF("暴力", "自动Peek", "Show indicator"),"显示指示器")
        NM(RF("暴力", "自动Peek", "Type"),"模式")
            RF("暴力", "自动Peek", "模式"):SetOptions("按住","切换")
        NM(RF("暴力", "自动Peek", "Maintain Origin"),"复位")
    NM(RF("暴力", "Accuracy"),"数值")
        for i = 1, 11, 1 do
            NM(RF("暴力", "数值", WeaponList[i], "Min Damage"),"最小伤害")
            NM(RF("暴力", "数值", WeaponList[i], "Min Damage Options", "Auto Wall"),"自动穿墙")
            NM(RF("暴力", "数值", WeaponList[i], "Min Damage Options", "Adaptive Damage"),"自适应伤害")
            NM(RF("暴力", "数值", WeaponList[i], "Hit Chance"),"命中率")
        end
    NM(RF("暴力", "Hitbox"),"部位")
        for i = 1, 11, 1 do
            NM(RF("暴力", "部位", WeaponList[i], "Head", "Priority"),"优先")
            NM(RF("暴力", "部位", WeaponList[i], "Head", "Exposed"),"暴露")
            NM(RF("暴力", "部位", WeaponList[i], "Head", "Center"),"中心")
            NM(RF("暴力", "部位", WeaponList[i], "Body", "Priority"),"优先")
            NM(RF("暴力", "部位", WeaponList[i], "Body", "Lethal"),"致命")
            NM(RF("暴力", "部位", WeaponList[i], "Body", "Exposed"),"暴露")
            NM(RF("暴力", "部位", WeaponList[i], "Body", "Center"),"中心")
            NM(RF("暴力", "部位", WeaponList[i], "Limbs", "Exposed"),"暴露")
            NM(RF("暴力", "部位", WeaponList[i], "Limbs", "Center"),"中心")
        end
    NM(RF("暴力", "Automate"),"自动")
        -- 自动急停
        for i = 1, 11, 1 do
            NM(RF("暴力", "自动", WeaponList[i], "Auto Stop"),"自动急停")
                NM(RF("暴力", "自动", WeaponList[i], "自动急停", "Stop"),"急停")
                NM(RF("暴力", "自动", WeaponList[i], "自动急停", "Slow Walk"),"慢走")
                NM(RF("暴力", "自动", WeaponList[i], "自动急停", "Duck"),"蹲下")
                NM(RF("暴力", "自动", WeaponList[i], "自动急停", "Early"),"提前")
                NM(RF("暴力", "自动", WeaponList[i], "自动急停", "Between Shots"),"射击间隙")
        end
        -- Shared
        NM(RF("暴力", "自动", "Shared", "Auto Fire"),"自动开火")
            NM(RF("暴力", "自动", "Shared", "自动开火", "Auto Pistol"),"自动手枪")
            NM(RF("暴力", "自动", "Shared", "自动开火", "Auto Revolver"),"左轮自动预热")
        NM(RF("暴力", "自动", "Shared", "Auto Scope"),"自动开关镜")
            NM(RF("暴力", "自动", "Shared", "自动开关镜", "Scope"),"自动开镜")
            NM(RF("暴力", "自动", "Shared", "自动开关镜", "Unscope"),"自动关镜")
        -- Pistol
        NM(RF("暴力", "自动", "Pistol", "Auto Fire"),"自动开火")
            NM(RF("暴力", "自动", "Pistol", "自动开火", "Auto Pistol"),"自动手枪")
        -- Heavy Pistol
        NM(RF("暴力", "自动", "Heavy Pistol", "Auto Fire"),"自动开火")
            NM(RF("暴力", "自动", "Heavy Pistol", "自动开火", "Auto Pistol"),"自动手枪")
            NM(RF("暴力", "自动", "Heavy Pistol", "自动开火", "Auto Revolver"),"左轮自动预热")
        -- Scout
        NM(RF("暴力", "自动", "Scout", "Auto Fire"),"自动开火")
            NM(RF("暴力", "自动", "Scout", "自动开火", "Auto Pistol"),"自动手枪")
        NM(RF("暴力", "自动", "Scout", "Auto Scope"),"自动开关镜")
            NM(RF("暴力", "自动", "Scout", "自动开关镜", "Scope"),"自动开镜")
            NM(RF("暴力", "自动", "Scout", "自动开关镜", "Unscope"),"自动关镜")
        -- Auto Sniper
        NM(RF("暴力", "自动", "Auto Sniper", "Auto Scope"),"自动开关镜")
            NM(RF("暴力", "自动", "Auto Sniper", "自动开关镜", "Scope"),"自动开镜")
            NM(RF("暴力", "自动", "Auto Sniper", "自动开关镜", "Unscope"),"自动关镜")
        -- Sniper
        NM(RF("暴力", "自动", "Sniper", "Auto Fire"),"自动开火")
            NM(RF("暴力", "自动", "Sniper", "自动开火", "Auto Pistol"),"自动手枪")
        NM(RF("暴力", "自动", "Sniper", "Auto Scope"),"自动开关镜")
            NM(RF("暴力", "自动", "Sniper", "自动开关镜", "Scope"),"自动开镜")
            NM(RF("暴力", "自动", "Sniper", "自动开关镜", "Unscope"),"自动关镜")

NM(RF("Visuals"),"视觉")
    NM(RF("视觉", "Enemy"),"敌人")
        NM(RF("视觉", "敌人", "Overlay"),"预览")
            NM(RF("视觉", "敌人", "预览", "Box"),"方框")
                NM(RF("视觉", "敌人", "预览", "方框", "Style"),"样式")
                    RF("视觉", "敌人", "预览", "方框", "样式"):SetOptions("粗线","细线")
                NM(RF("视觉", "敌人", "预览", "方框", "Precision"),"精确模式")
                NM(RF("视觉", "敌人", "预览", "方框", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Ammo"),"弹药")
                NM(RF("视觉", "敌人", "预览", "弹药", "Ammo Full Color"),"满弹药颜色")
                NM(RF("视觉", "敌人", "预览", "弹药", "Ammo Empty Color"),"空弹药颜色")
            NM(RF("视觉", "敌人", "预览", "Health"),"生命")
                NM(RF("视觉", "敌人", "预览", "生命", "Health Bar"),"生命条")
                    NM(RF("视觉", "敌人", "预览", "生命", "生命条", "Health Max Color"),"满生命颜色")
                    NM(RF("视觉", "敌人", "预览", "生命", "生命条", "Health Low Color"),"低生命颜色")
                NM(RF("视觉", "敌人", "预览", "生命", "Health Number"),"生命数值")
            NM(RF("视觉", "敌人", "预览", "Name"),"名字")
                NM(RF("视觉", "敌人", "预览", "名字", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Skeleton"),"骨骼")
                NM(RF("视觉", "敌人", "预览", "骨骼", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Armor"),"护甲")
                NM(RF("视觉", "敌人", "预览", "护甲", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Money"),"金钱")
                NM(RF("视觉", "敌人", "预览", "金钱", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Ping"),"延迟")
                NM(RF("视觉", "敌人", "预览", "延迟", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Flags"),"标志")
                NM(RF("视觉", "敌人", "预览", "标志", "Defusing"),"拆弹中")
                NM(RF("视觉", "敌人", "预览", "标志", "Planting"),"安包中")
                NM(RF("视觉", "敌人", "预览", "标志", "Scoped"),"开镜中")
                NM(RF("视觉", "敌人", "预览", "标志", "Reloading"),"换弹中")
                NM(RF("视觉", "敌人", "预览", "标志", "Pin Pulled"),"已拉环")
                NM(RF("视觉", "敌人", "预览", "标志", "Flashed"),"被闪中")
                NM(RF("视觉", "敌人", "预览", "标志", "Has Defuser"),"有钳子")
                NM(RF("视觉", "敌人", "预览", "标志", "Has C4"),"带包")
            NM(RF("视觉", "敌人", "预览", "Barrel"),"枪口")
            NM(RF("视觉", "敌人", "预览", "Weapon"),"武器")
        NM(RF("视觉", "敌人", "Chams"),"上色")
    NM(RF("视觉", "Team"),"队友")
    NM(RF("视觉", "Weapon"),"武器")
    NM(RF("视觉", "Local"),"自身")

print("汉化已加载, 请勿重复加载脚本")